# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: build-branch
on:
  - push
  - pull_request
jobs:
  unit:
    name: unit
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        profile:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
      fail-fast: false
    steps:
        # TEMPORARY WHILE GITHUB FIXES https://github.com/actions/virtual-environments/issues/3185
        - name: Add the current IP address, long hostname and short hostname record to /etc/hosts file
          run: |
            echo -e "$(ip addr show eth0 | grep "inet\b" | awk '{print $2}' | cut -d/ -f1)\t$(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
        # REMOVE CODE ABOVE WHEN ISSUE IS ADDRESSED!
        - uses: actions/checkout@v3
        - name: Cache for maven dependencies
          uses: actions/cache@v3
          with:
            path: ~/.m2/repository
            key: maven-repo-${{ hashFiles('**/pom.xml') }}-${{ github.job }}
            restore-keys: |
              maven-repo-${{ hashFiles('**/pom.xml') }}
              maven-repo-
        - run: ./dev-support/checks/unit.sh -Dtest=TestNettyDataStreamChainTopologyWithGrpcCluster -Dsurefire.failIfNoSpecifiedTests=false
          env:
            ITERATIONS: 40
        - name: Summary of failures
          run: cat target/${{ github.job }}/summary.txt
          if: ${{ !cancelled() }}
        - uses: actions/upload-artifact@v3
          if: ${{ !cancelled() }}
          with:
            name: unit-${{ matrix.profile }}
            path: target/unit
        - name: Delete temporary build artifacts
          run: rm -rf ~/.m2/repository/org/apache/ratis
          if: always()
